require: rubocop-rails

AllCops:
  Exclude:
    - 'bin/**/*'
    - 'node_modules/**/*'
    - 'vendor/**/*'
  NewCops: enable
  SuggestExtensions: false

Layout/LeadingCommentSpace:
  Exclude:
    - 'Gemfile'

Layout/LineLength:
  Exclude:
    - 'app/views/**/*.jbuilder'
    - 'app/models/feedbin.rb'
    - 'config/routes.rb'

Metrics/BlockLength:
  Exclude:
    - 'config/routes.rb'
    - 'spec/**/*'

Style/Documentation:
  Enabled: false

Style/FrozenStringLiteralComment:
  Enabled: false

Rails/ApplicationController:
  Exclude:
    - 'app/controllers/api_controller.rb'
