AllCops:
  Exclude:
    - 'bin/**/*'
    - 'node_modules/**/*'
    - 'vendor/**/*'

Layout/LeadingCommentSpace:
  Exclude:
    - 'Gemfile'

Metrics/BlockLength:
  Exclude:
    - 'spec/**/*'

Metrics/LineLength:
  Exclude:
    - 'app/views/**/*.jbuilder'

Style/Documentation:
  Enabled: false

Style/FrozenStringLiteralComment:
  Enabled: false
