version: 2

jobs:
  test:
    working_directory: ~/monolithium
    docker:
      - image: cimg/ruby:3.3.0-browsers
        environment:
          RAILS_ENV: test
      - image: cimg/postgres:14.10

    steps:
      - checkout

      - restore_cache:
          name: Restore bundler cache
          key: bundler-{{ checksum "Gemfile.lock" }}

      - run:
          name: Bundle install
          command: bundle install --jobs=4 --retry=3 --path vendor/bundle

      - save_cache:
          name: Save bundler cache
          key: bundler-{{ checksum "Gemfile.lock" }}
          paths:
            - vendor/bundle

      - run:
          name: Setup database
          command: mv config/database{.circle,}.yml && bundle exec rake db:create db:migrate

      - run:
          name: Compile assets
          command: bundle exec rake assets:precompile

      - run:
          name: Run tests
          command: bundle exec rake

workflows:
  version: 2
  default:
    jobs:
      - test
