version: 2

jobs:
  build:
    working_directory: ~/monolithium
    docker:
      - image: circleci/ruby:2.5.0-node-browsers
        environment:
          RAILS_ENV: test
      - image: circleci/postgres:10.1-alpine

    steps:
      - checkout

      - restore_cache:
          key: monolithium-{{ checksum "Gemfile.lock" }}

      - run:
          name: Bundle install
          command: bundle install --jobs=4 --retry=3 --path vendor/bundle

      - save_cache:
          key: monolithium-{{ checksum "Gemfile.lock" }}
          paths:
            - vendor/bundle
      - run: yarn install

      - run: mv config/database{.circle,}.yml
      - run: bundle exec rake db:create db:migrate
      - run: bundle exec rake webpacker:compile

      - run:
          name: Tests
          command: bundle exec rake
