# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

shared:
  feedbin_username: <%= ENV['FEEDBIN_USERNAME'] %>
  feedbin_password: <%= ENV['FEEDBIN_PASSWORD'] %>

# Environmental secrets are only available for that specific environment.

development:
  admin_password: shhh
  client_token: shhh
  secret_key_base: 6a5341fa5e7e62d144961615bf689f6fbe223331370b316df623f1f34102fe16a4d5f863a84adca18345211d5d83cf4811af4735f2d483be129a465c1f2f429b

test:
  admin_password: shhh
  client_token: shhh
  secret_key_base: 441b32a8fe24aa221e31087529f3dfde526fefb648ca4378084d78f66bbdede88a820163662732ec2d559d7487646a4ce543563a8df394d9f38e2c4c2583ada8

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  admin_password: <%= ENV["ADMIN_PASSWORD"] %>
  client_token: <%= ENV["CLIENT_TOKEN"] %>
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
  user_token: <%= ENV["USER_TOKEN"] %>
